pool:
  vmImage: 'macos-latest'
  demands:
  - java
  - JDK

steps:

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleRelease makeUniversalPkg'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/universal'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/outputs'
    CleanTargetFolder: true
    OverWrite: true
    preserveTimestamp: true

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)/outputs/'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'e0256516-4c8d-4265-8edc-b3309388a503/3b62aae3-ca93-461a-9def-24bea0b1fe25'
    vstsFeedPackagePublish: 'fluentuiandroid'
    versionOption: 'patch'
    packagePublishDescription: 'Fluent Universal Package'
    publishedPackageVar: 'fluent package'
  
